" Pathogen plugin (to keep all other plugins in plugins/)
execute pathogen#infect('plugins/{}')

" Powerline plugin
let g:Powerline_symbols = 'fancy'

" Show line numbers
set number

" Show matching braces
set showmatch

" Incremental search with ignore case (except explicit caps)
" Highlight all search results, and use \q to unhighight
set incsearch
set ic
set smartcase
set hlsearch
nmap \q :nohlsearch<CR>

" Makes vim behave in a more useful way than vi-compatible mode
set nocompatible

" Set tab character to 4 characters for hardtab
set tabstop=4
set shiftwidth=4

" Turn tabs into whitespace (softtab)
" set expandtab
" set softtabstop=4

" Syntax highlighting and colorscheme
syntax enable
set bg=dark
colorscheme solarized

" Fold method
set foldmethod=syntax
set nofoldenable
set foldlevel=1

" Make any text wider than 80 char highlight in red
"highlight OverLength ctermbg=red ctermfg=white guibg=#592929
"match OverLength /\%81v.\+/

" Tag file
set tags=

" Change text encoding to Japanese Shift-JIS with Ctrl-J
:map <C-j> :set encoding=sjis<CR>:set fileencodings=cp932<CR>:e!<CR>

" Enable 
filetype plugin indent on

" Disable arrow keys to force learning hjkl
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>

" Some tricks for mutt
" F1 through F3 re-wraps paragraphs in useful ways
augroup MUTT
  au BufRead ~/.mutt/temp/mutt* set spell " <-- vim 7 required
  au BufRead ~/.mutt/temp/mutt* nmap  <F1>  gqap
  au BufRead ~/.mutt/temp/mutt* nmap  <F2>  gqqj
  au BufRead ~/.mutt/temp/mutt* nmap  <F3>  kgqj
  au BufRead ~/.mutt/temp/mutt* map!  <F1>  <ESC>gqapi
  au BufRead ~/.mutt/temp/mutt* map!  <F2>  <ESC>gqqji
  au BufRead ~/.mutt/temp/mutt* map!  <F3>  <ESC>kgqji
augroup END

" Map key for TagList plugin (show functions)
map ff :TlistOpen<CR>

" Map key for CtrlP
nmap ; :CtrlPMixed<CR>

" Make j/k move one single row instead of one single line
nnoremap j gj
nnoremap k gk

" Hotkeys for toggle of line numbers and paste mode
nmap \l :setlocal number!<CR>
nmap \p :set paste!<CR>

" Make sure 256 color terminal support is used
if $TERM == "xterm-256color" || $TERM == "screen-256color" || $COLORTERM == "gnome-terminal"
    set t_Co=256
endif
