# Aliases -----------------------------------------------------------------
alias ls='ls -GF'
alias grep='grep -nH'
alias lock="open /System/Library/Frameworks/ScreenSaver.framework/Versions/A/Resources/ScreenSaverEngine.app"


# Variables ---------------------------------------------------------------
export PS1="[\#][\u@\h][\w] ";
export PATH=$PATH:/usr/local/sbin:/usr/local/bin:/Users/backalor/Scripts
export GPGKEY=FFFFFFFF
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export GIT_EDITOR=vi


# Settings ----------------------------------------------------------------
set meta-flag on
set input-meta on
set output-meta on
set convert-meta off
